var payloads = {
	50: 'ERROR_RES',
	51: 'HEARTBEAT_EVENT',
	52: 'PING_REQ',
	53: 'PING_RES',
	2000: 'AUTH_REQ',
	2001: 'AUTH_RES',
	2002: 'OA_SUBSCRIBE_FOR_TRADING_EVENTS_REQ',
	2003: 'OA_SUBSCRIBE_FOR_TRADING_EVENTS_RES',
	2004: 'OA_UNSUBSCRIBE_FROM_TRADING_EVENTS_REQ',
	2005: 'OA_UNSUBSCRIBE_FROM_TRADING_EVENTS_RES',
	2006: 'OA_GET_SUBSCRIBED_ACCOUNTS_REQ',
	2007: 'OA_GET_SUBSCRIBED_ACCOUNTS_RES',
	2013: 'OA_CREATE_ORDER_REQ',
	2016: 'OA_EXECUTION_EVENT',
	2017: 'OA_CANCEL_ORDER_REQ',
	2018: 'OA_CLOSE_POSITION_REQ',
	2019: 'OA_AMEND_POSITION_SL_TP_REQ',
	2020: 'OA_AMEND_ORDER_REQ',
	2021: 'OA_SUBSCRIBE_FOR_SPOTS_REQ',
	2022: 'OA_SUBSCRIBE_FOR_SPOTS_RES',
	2023: 'OA_UNSUBSCRIBE_FROM_SPOTS_REQ',
	2024: 'OA_UNSUBSCRIBE_FROM_SPOTS_RES',
	2025: 'OA_GET_SPOT_SUBSCRIPTION_REQ',
	2026: 'OA_GET_SPOT_SUBSCRIPTION_RES',
	2027: 'OA_GET_ALL_SPOT_SUBSCRIPTIONS_REQ',
	2028: 'OA_GET_ALL_SPOT_SUBSCRIPTIONS_RES',
	2029: 'OA_SPOT_EVENT'

};

exports.getPayloadName = function (payload) {
	return payloads[payload];
};